
import { t as uiText } from "@/lib/i18n";
export const siteConfig = {
  name: "PerfectPPI",
  description:
    uiText("ui.professional_pre_purchase_vehicle_inspection_ce4a3d0e79"),
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://www.perfectppi.com",
} as const;

export const navConfig = {
  public: [
    { label: uiText("ui.home_3a78695388"), href: "/" },
    { label: uiText("ui.marketplace_c608981d8d"), href: "/marketplace" },
    { label: uiText("ui.community_bb501d7877"), href: "/community" },
    { label: uiText("ui.find_a_technician_8f8aff766b"), href: "/technicians" },
  ],
  dashboard: [
    { label: uiText("ui.dashboard_67b6964686"), href: "/dashboard", icon: "LayoutDashboard" },
    { label: uiText("ui.garage_b15f625351"), href: "/dashboard/vehicles", icon: "Car" },
    { label: uiText("ui.listings_5009238dba"), href: "/dashboard/listings", icon: "Tag" },
    { label: uiText("ui.posts_a80811cf68"), href: "/dashboard/posts", icon: "Newspaper" },
    { label: uiText("ui.friends_bd104d1b98"), href: "/dashboard/friends", icon: "Users" },
    { label: uiText("ui.saved_b5c120b316"), href: "/dashboard/saved", icon: "Bookmark" },
    { label: uiText("ui.inspections_20cbe85cdd"), href: "/dashboard/ppi", icon: "ClipboardCheck" },
    { label: uiText("ui.warranties_c6aa176bba"), href: "/dashboard/warranty", icon: "Shield" },
    { label: uiText("ui.messages_04d7b48339"), href: "/dashboard/messages", icon: "MessageSquare" },
    { label: uiText("ui.media_d357175cfe"), href: "/dashboard/media", icon: "Image" },
    { label: uiText("ui.profile_d696a35bdd"), href: "/dashboard/profile", icon: "User" },
    { label: uiText("ui.settings_74a883a037"), href: "/dashboard/settings", icon: "Settings" },
  ],
  tech: [
    { label: uiText("ui.dashboard_67b6964686"), href: "/tech", icon: "LayoutDashboard" },
    { label: uiText("ui.inspections_20cbe85cdd"), href: "/tech/ppi", icon: "ClipboardCheck" },
    { label: uiText("ui.reviews_84cb7871b7"), href: "/tech/reviews", icon: "Star" },
    { label: uiText("ui.profile_d696a35bdd"), href: "/tech/profile", icon: "User" },
    { label: uiText("ui.organization_d764d42592"), href: "/tech/organization", icon: "Building2" },
    { label: uiText("ui.messages_04d7b48339"), href: "/tech/messages", icon: "MessageSquare" },
  ],
  org: [
    { label: uiText("ui.dashboard_67b6964686"), href: "/org", icon: "LayoutDashboard" },
    { label: uiText("ui.technicians_8bb7fac529"), href: "/org/technicians", icon: "Users" },
    { label: uiText("ui.inspections_20cbe85cdd"), href: "/org/inspections", icon: "ClipboardCheck" },
    { label: uiText("ui.dealerspace_7d7288383a"), href: "/org/inspections/dealerspace", icon: "Plug" },
    // Managers can be assigned inspections themselves; this is their own queue,
    // not the organization-wide list above.
    { label: uiText("ui.my_inspections_944292ab1e"), href: "/tech/ppi", icon: "Wrench" },
    { label: uiText("ui.profile_d696a35bdd"), href: "/org/profile", icon: "Building2" },
    { label: uiText("ui.messages_04d7b48339"), href: "/org/messages", icon: "MessageSquare" },
    { label: uiText("ui.settings_74a883a037"), href: "/org/settings", icon: "Settings" },
  ],
  admin: [
    { label: uiText("ui.overview_d4b1ea5708"), href: "/admin", icon: "LayoutDashboard" },
    { label: uiText("ui.users_6b0cc904d0"), href: "/admin/users", icon: "Users" },
    { label: uiText("ui.vehicles_9113796a52"), href: "/admin/vehicles", icon: "Car" },
    { label: uiText("ui.listings_5009238dba"), href: "/admin/listings", icon: "Tag" },
    { label: uiText("ui.community_bb501d7877"), href: "/admin/community", icon: "Newspaper" },
    { label: uiText("ui.moderation_126d441544"), href: "/admin/moderation", icon: "ShieldAlert" },
    { label: uiText("ui.moderation_access_0a48338aad"), href: "/admin/moderation/access", icon: "Shield" },
    { label: uiText("ui.evidence_retention_2fa5ad947c"), href: "/admin/moderation/retention", icon: "ScrollText" },
    { label: uiText("ui.feature_flags_c60c04dc77"), href: "/admin/flags", icon: "ToggleLeft" },
    { label: uiText("ui.social_readiness_159d6835e5"), href: "/admin/social-readiness", icon: "ListChecks" },
    { label: uiText("ui.product_analytics_9fd4c15283"), href: "/admin/analytics", icon: "ChartNoAxesColumnIncreasing" },
    { label: uiText("ui.technicians_8bb7fac529"), href: "/admin/technicians", icon: "Wrench" },
    { label: uiText("ui.review_disputes_25c25858ef"), href: "/admin/reviews", icon: "Star" },
    { label: uiText("ui.organizations_2730183d6b"), href: "/admin/organizations", icon: "Building2" },
    {
      label: uiText("ui.inspections_20cbe85cdd"),
      href: "/admin/inspections",
      icon: "ClipboardCheck",
    },
    { label: uiText("ui.outputs_e7ce99764a"), href: "/admin/outputs", icon: "FileText" },
    { label: uiText("ui.warranties_c6aa176bba"), href: "/admin/warranties", icon: "Shield" },
    { label: uiText("ui.contracts_0488acc63d"), href: "/admin/contracts", icon: "FileSignature" },
    { label: uiText("ui.payments_632e1c5839"), href: "/admin/payments", icon: "CreditCard" },
    { label: uiText("ui.messages_04d7b48339"), href: "/admin/messages", icon: "MessageSquare" },
    {
      label: uiText("ui.communications_919a92533f"),
      href: "/admin/communications",
      icon: "MessageSquare",
    },
    { label: uiText("ui.audit_log_47751f88ed"), href: "/admin/audit", icon: "ScrollText" },
    { label: uiText("ui.settings_74a883a037"), href: "/admin/settings", icon: "Settings" },
  ],
  dev: [{ label: uiText("ui.role_switcher_985d508cd2"), href: "/dev", icon: "Code2" }],
} as const;
