import { describe, test } from "node:test";
import assert from "node:assert/strict";
import { PDFDocument } from "pdf-lib";
import sharp from "sharp";

import { evaluateInspection } from "../../src/features/ppi/inspection-rules.ts";
import { buildInspectionReport } from "../../src/features/ppi/inspection-report.ts";
import { fitReportToLayout } from "../../src/lib/pdf/inspection-report/fit.ts";
import {
  renderBlankOverviewTemplate,
  renderBlankVisualTemplate,
  renderInspectionReportPdf,
} from "../../src/lib/pdf/inspection-report/render.ts";
import { buildReportViewModel } from "../../src/lib/pdf/inspection-report/view-model.ts";
import { loadLayoutAssets } from "../../src/lib/pdf/inspection-report/canvas.ts";
import { renderEvidenceAppendixPdf, type AppendixViewModel } from "../../src/lib/pdf/inspection-report/appendix.ts";
import { evaluateDentsTiresCoverageFromFacts } from "../../src/features/warranty/dents-tires-coverage.ts";
import { validateAnswers, JevError } from "../../src/lib/ai/jev.ts";
import { completeSample, dentsSample, sampleViewModel } from "./inspection-report-samples.mts";
import {
  INSPECTION_DATE,
  buildFacts,
  cleanCorner,
  cleanObservations,
  observed,
  unavailable,
  v2Sections,
} from "./inspection-v2-fixtures.mts";

async function pageCount(bytes: Buffer) {
  return (await PDFDocument.load(bytes)).getPageCount();
}

const FORBIDDEN = /\b(AI|artificial intelligence|AI-generated|generated by)\b|\$\s?\d|\bdollars?\b/i;

function visibleText(vm: Awaited<ReturnType<typeof sampleViewModel>>["vm"]): string {
  return [
    vm.priority,
    vm.limitations,
    ...vm.overview.flatMap((block) => [block.title, block.observation, block.action]),
    ...vm.body.map((item) => item.text),
    ...Object.values(vm.tires).flatMap((tire) => Object.values(tire).map(String)),
  ].join("\n");
}

describe("two-page inspection report", () => {
  test("both scopes render exactly two US Letter pages", async () => {
    for (const facts of [completeSample(), dentsSample()]) {
      const { vm, overflow } = await sampleViewModel(facts);
      assert.deepEqual(overflow, []);
      const bytes = await renderInspectionReportPdf(vm);
      const doc = await PDFDocument.load(bytes);
      assert.equal(doc.getPageCount(), 2);
      for (const page of doc.getPages()) {
        assert.deepEqual([page.getWidth(), page.getHeight()], [612, 792]);
      }
      assert.doesNotMatch(visibleText(vm), FORBIDDEN);
    }
  });

  test("blank templates are single pages with no default green checks", async () => {
    assert.equal(await pageCount(await renderBlankVisualTemplate("complete")), 1);
    assert.equal(await pageCount(await renderBlankVisualTemplate("dents_tires")), 1);
    assert.equal(await pageCount(await renderBlankOverviewTemplate("dents_tires")), 1);
  });

  test("a dense urgent inspection keeps every urgent corner and stays on two pages", async () => {
    const worstCorner = (corner: string) => cleanCorner(corner, {
      [`tires.${corner}.damage`]: observed({
        defects: [
          { id: `${corner.replace("_", "")}-a`, type: "puncture", location: "tread" },
          { id: `${corner.replace("_", "")}-b`, type: "bulge", location: "sidewall" },
        ],
      }),
      [`tires.${corner}.cracking`]: observed({ level: "severe" }),
      [`tires.${corner}.tread`]: observed({ reading: "1", unit: "thirty_seconds_inch", method: "tread_depth_gauge" }),
      [`tires.${corner}.pressure`]: observed({ reading: "26", unit: "psi", context: "cold", method: "pressure_gauge" }),
      [`wheels.${corner}.damage`]: observed({ defects: [{ id: `${corner.replace("_", "")}-w`, type: "cracked" }] }),
    });
    const observations = {
      ...cleanObservations("dents_tires"),
      ...worstCorner("front_left"),
      ...worstCorner("front_right"),
      ...worstCorner("rear_left"),
      ...worstCorner("rear_right"),
      "body.hood.condition": observed({ condition: "damage_present", defects: [{ id: "hood-1", type: "dent", severity: "severe", structural: true, note: "Buckled near the latch." }] }),
      "body.left_front_door.condition": observed({ condition: "damage_present", defects: [{ id: "lfd-1", type: "scratch", severity: "moderate" }] }),
      "body.roof.condition": observed({ condition: "damage_present", defects: [{ id: "roof-1", type: "dent", severity: "minor" }] }),
      "body.left_rear_quarter.condition": observed({ condition: "damage_present", defects: [{ id: "lrq-1", type: "rust", severity: "severe" }] }),
      "body.right_rocker.condition": observed({ condition: "damage_present", defects: [{ id: "rr-1", type: "paint_damage", severity: "minor" }] }),
    };
    const facts = buildFacts("dents_tires", v2Sections("dents_tires", observations));
    const { report, vm, overflow } = await sampleViewModel(facts);
    // Every corner is named, either individually or as "all four".
    assert.match(report.priority_actions, /Replace all four tires/);
    assert.match(report.priority_actions, /all four wheel and tire assemblies/);
    // A service step shared by several tires is one sentence, not one per tire.
    assert.equal(report.priority_actions.match(/placard pressure/g)?.length, 1);
    assert.match(report.priority_actions, /Set all four tires to the placard pressure and recheck\./);
    if (overflow.length === 0) {
      assert.equal(await pageCount(await renderInspectionReportPdf(vm)), 2);
    } else {
      assert.equal(report.status, "needs_review", "unfit urgent content is held, never clipped");
    }
  });

  test("long names and accented characters are kept", async () => {
    const facts = completeSample();
    facts.vehicle.make = "Mercedes-Benz";
    facts.vehicle.model = "GLE 450 4MATIC Coupé with an unusually long trim description";
    facts.inspector.name = "Zoë Łukasiewicz-Øster de la Fontaine-Hernández";
    const { vm } = await sampleViewModel(facts);
    assert.equal(await pageCount(await renderInspectionReportPdf(vm)), 2);
  });

  test("an all-unknown historical inspection renders with no clean statuses", async () => {
    const facts = buildFacts("dents_tires", v2Sections("dents_tires", {}), { catalogVersion: 1 });
    const assessment = evaluateInspection(facts, { inspectionDate: new Date(INSPECTION_DATE) });
    const report = (await fitReportToLayout(buildInspectionReport({ facts, assessment, factsHash: null, generatedAt: INSPECTION_DATE }))).report;
    const vm = buildReportViewModel(report, { submissionId: "5a3c9e10-0000-4000-8000-000000000009", outputVersion: 2, diagram: loadLayoutAssets().spec.diagram });
    for (const tire of Object.values(vm.tires)) assert.notEqual(tire.status, "checked");
    assert.equal(vm.certified, false);
    assert.match(vm.certification_time, /Certification not recorded/);
    assert.equal(await pageCount(await renderInspectionReportPdf(vm)), 2);
  });

  test("self-inspection unavailable readings are disclosed on both pages", async () => {
    const { vm } = await sampleViewModel(dentsSample());
    assert.equal(vm.tires.rear_left.tread, "Unavailable");
    assert.equal(vm.tires.rear_left.partial, true);
    const unavailable = vm.overview.find((block) => block.title === "UNAVAILABLE MEASUREMENTS");
    assert.match(unavailable?.observation ?? "", /Tread and pressure not measured: rear-left\./);
  });
});

describe("photo evidence appendix", () => {
  test("every photo is included with no page cap, and missing photos get placeholders", async () => {
    const jpeg = await sharp({ create: { width: 64, height: 48, channels: 3, background: "#888888" } }).jpeg().toBuffer();
    const photos = Array.from({ length: 40 }, (_, index) => ({
      evidence_id: `E${String(index + 1).padStart(2, "0")}`,
      media_id: `media-${index}`,
      title: `Photo ${index + 1}`,
      association: "No linked finding | unlinked upload | Wheels & Tires",
      caption: index === 3 ? `${"A very long inspector caption. ".repeat(60)}END-SENTINEL` : "No caption recorded.",
      provenance: "Uploaded Sep 22, 2026",
      image: index % 10 === 9 ? null : { jpeg: new Uint8Array(jpeg), width: 64, height: 48 },
      unavailable_reason: index % 10 === 9 ? "The photo could not be retrieved or decoded." : null,
    }));
    const vm: AppendixViewModel = {
      report_ref: "PPI-TEST / v1",
      vehicle: "2021 Sample Touring Sedan",
      date: "Sep 22, 2026",
      inspector: "Jordan Lee | Technician",
      scope_label: "Complete Inspection",
      certification_line: "Certified",
      generated_line: "Sep 23, 2026",
      findings: Array.from({ length: 30 }, (_, index) => ({ ref: `T${index + 1}`, status: "monitor" as const, title: `Finding ${index + 1}`, text: "Observation. Significance. Next step." })),
      answers: Array.from({ length: 90 }, (_, index) => ({ section: "Exterior", prompt: `Question ${index + 1}`, value: "Recorded value" })),
      notes: [{ section: "Exterior", text: "Inspector note as recorded." }],
      photos,
      other_media: [{ evidence_id: "E41", media_id: "video-1", type: "Video", association: "Road Test" }],
    };
    const result = await renderEvidenceAppendixPdf(vm);
    assert.equal(result.renderedPhotoIds.length + result.placeholderPhotoIds.length, 40);
    assert.equal(result.placeholderPhotoIds.length, 4);
    assert.ok(result.pageCount > 40, `expected more than 40 pages, got ${result.pageCount}`);
    assert.equal(await pageCount(result.bytes), result.pageCount);
  });
});

describe("typed Dents & Tires coverage adapter", () => {
  function coverage(observations: Record<string, unknown>) {
    return evaluateDentsTiresCoverageFromFacts(buildFacts("dents_tires", v2Sections("dents_tires", { ...cleanObservations("dents_tires"), ...observations })));
  }
  const component = (result: ReturnType<typeof coverage>, name: string) => result.components.find((entry) => entry.component === name);

  test("the exact 2/32 threshold holds across units", () => {
    assert.equal(component(coverage({ "tires.front_left.tread": observed({ reading: "2", unit: "thirty_seconds_inch", method: "tread_depth_gauge" }) }), "Front Left Tire")?.determination, "covered");
    assert.equal(component(coverage({ "tires.front_left.tread": observed({ reading: "1.5875", unit: "mm", method: "tread_depth_gauge" }) }), "Front Left Tire")?.determination, "covered");
    assert.equal(component(coverage({ "tires.front_left.tread": observed({ reading: "1.59", unit: "mm", method: "tread_depth_gauge" }) }), "Front Left Tire")?.determination, "excluded");
    assert.equal(component(coverage({ "tires.front_left.tread": unavailable("no_gauge") }), "Front Left Tire")?.determination, "excluded");
  });

  test("a puncture replacement recommendation never grants coverage", () => {
    const result = coverage({ "tires.front_left.damage": observed({ defects: [{ id: "abcd1", type: "puncture" }] }) });
    assert.equal(component(result, "Front Left Tire")?.determination, "excluded");
    assert.equal(component(result, "Wheels / Rims")?.determination, "excluded");
    assert.equal(result.overall_eligibility, "ineligible");
  });

  test("wheel damage feeds Wheels / Rims; doors roll up; bumpers stay excluded", () => {
    const result = coverage({
      "wheels.rear_right.damage": observed({ defects: [{ id: "abcd2", type: "scratch_curb_rash" }] }),
      "body.left_rear_door.condition": observed({ condition: "damage_present", defects: [{ id: "abcd3", type: "dent" }] }),
      "body.roof.condition": observed({ condition: "damage_present", defects: [{ id: "abcd4", type: "scratch" }] }),
    });
    assert.equal(component(result, "Wheels / Rims")?.determination, "covered");
    assert.equal(component(result, "Left Door")?.determination, "covered");
    assert.equal(component(result, "Body Panels")?.determination, "covered");
    assert.equal(component(result, "Bumper")?.determination, "excluded");
  });
});

describe("Jev response validation", () => {
  const questions = {
    note_category: { type: "choice" as const, instructions: "x", criteria: { a: "A", insufficient_evidence: "?" } },
  };

  test("accepts a well-formed answer", () => {
    const result = validateAnswers({ note_category: { choice: "a", probabilities: { a: 0.9, insufficient_evidence: 0.1 }, confidence: 0.9 } }, questions);
    assert.equal(result.note_category.choice, "a");
  });

  test("rejects unknown options, missing keys and invalid probabilities", () => {
    assert.throws(() => validateAnswers({ note_category: { choice: "b", probabilities: {}, confidence: 0.5 } }, questions), JevError);
    assert.throws(() => validateAnswers({}, questions), JevError);
    assert.throws(() => validateAnswers({ note_category: { choice: "a", probabilities: { a: 1.5 }, confidence: 0.5 } }, questions), JevError);
    assert.throws(() => validateAnswers({ note_category: { choice: "a", probabilities: { z: 0.5 }, confidence: 0.5 } }, questions), JevError);
  });
});
